In [1]:
# struct of python variable:
"""
struct _longobject{
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
}
"""

'\nstruct _longobject{\n    long ob_refcnt;\n    PyTypeObject *ob_type;\n    size_t ob_size;\n    long ob_digit[1];\n}\n'

In [2]:
# python lists
L = list(range(10))
L, type(L), type(L[0])

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], list, int)

In [3]:
L2 = [str(c) for c in L]
L2, type(L2), type(L2[0])

(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], list, str)

In [4]:
# hyterogeneous lists:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [5]:
# fixed-type arrays in python 
import array 
L = list(range(10))
A = array.array("i", L)
A 

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# creating arrays from python lists 
import numpy as np 

In [7]:
# integer array 
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [8]:
# NumPy arrays can only contain one type inside of it
np.array([3.14, 1,2])   # will cast all to floating point 

array([3.14, 1.  , 2.  ])

In [9]:
# set the type of arrays explicitly
np.array([1,2,3,4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [10]:
# nested lists result in multidimensional arrays 
np.array([range(i,i+3) for i in [2,4,5]])

array([[2, 3, 4],
       [4, 5, 6],
       [5, 6, 7]])

In [11]:
# creating a length-10 integer array filled with 0s 
np.zeros(10, dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# create a 3x5 floating point array filled with 1s 
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# create a 3x5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [14]:
# create an array filled with a linear sequence 
# starting at 0, ending at 20, stepping by 2 
# this is similar to the built-in range function 
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
# create an array of five values evenly spaced between 0 and 1 
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
# create a 3x3 array uniformly distributed 
# pseudorandom values between 0 and 1 
np.random.random((3,3))

array([[0.4480676 , 0.73248252, 0.13970107],
       [0.06171386, 0.7296459 , 0.36509086],
       [0.97524642, 0.84893999, 0.03965731]])

In [18]:
# create a 3x3 array of normally distributed pseudorandom 
# values with mean 0 and standard deviation 1 
np.random.normal(0,1, (3,3))

array([[-1.67484868, -1.2966733 ,  0.99673847],
       [ 0.07768923,  0.66306133,  0.64930305],
       [ 1.16852232, -0.12200966, -0.83141385]])

In [19]:
# create a 3x3 array of pseudorandom integers in the interval [0,10)
np.random.randint(0,10,(3,3))

array([[7, 2, 8],
       [9, 4, 6],
       [2, 5, 0]])

In [20]:
# create a 3x3 identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# create an uninitialized array of three integers; the values wuill be 
# whatever happens to alreadty exist at that memory location 
np.empty(3)

array([1., 1., 1.])

In [22]:
# standard data types 
np.zeros(10, dtype="int16")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)