In [ ]:
# attributes 
# indexing 
# slicing 
# reshaping 
# joining and splitting of arrays 

In [1]:
# attributes 
import numpy as np 
rng = np.random.default_rng(seed = 1701)

In [2]:
x1 = rng.integers(10, size=6)       # one dimension 
x2 = rng.integers(10, size=(3,4))   # two dimensions 
x3 = rng.integers(10, size=(3,4,5)) # three dimensions 


In [3]:
x3.ndim, x3.shape, x3.size, x3.dtype 

(3, (3, 4, 5), 60, dtype('int64'))

In [4]:
# indexing from the end of array 
x1[-2]

8

In [5]:
x2 

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [7]:
# row = 2 
# column = -2 
x2[2,-2]

6

In [8]:
# array slicing 
# x[start : stop : step]


In [9]:
x1 

array([9, 4, 0, 3, 8, 6])

In [10]:
# first three elements 
x1[:3]

array([9, 4, 0])

In [11]:
# elements after index 3 
# :_ mean "all" elements (each element to the end)
x1[3:]

array([3, 8, 6])

In [12]:
# middle subarray 
x1[1:4]

array([4, 0, 3])

In [13]:
# every second element 
x1[::2] 

array([9, 0, 8])

In [16]:
# every second element, starting at index 1 
# from 1 row 
# :_ each element to the end 
# with skip each second 
x1[1::2]

array([4, 3, 6])

In [17]:
# all elements reversed 
# from the beginning, each elements in reverse order 
x1[::-1]

array([6, 8, 3, 0, 4, 9])

In [18]:
# from index 4 to the end each second in reversed order 
x1[4::-2]

array([8, 0, 9])

In [19]:
x1

array([9, 4, 0, 3, 8, 6])

In [22]:
# index 2 was 0
# reversed order from 0 to the end 
# will be 0-4-9
x1[2::-1]

array([0, 4, 9])

In [24]:
# multidimensional subarrays 
x2 

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [26]:
# first two rows and three columns 
# get rows from beginning to the 2 
# get columns from the beginnine to the 3 
x2[:2, :3]

array([[3, 1, 3],
       [4, 0, 2]])

In [28]:
# three rows, every second column 
x2[:3, ::2]

array([[3, 3],
       [4, 2],
       [0, 6]])

In [29]:
# all rows and columns reversed 
x2[::-1, ::-1]

array([[9, 6, 0, 0],
       [3, 2, 0, 4],
       [7, 3, 1, 3]])

In [30]:
# first column of x2 
x2[:,0]

array([3, 4, 0])

In [31]:
# first row of x2
# from the index 0 or rows - only one
# from the beginning of columns to the end 
x2[0,:]

array([3, 1, 3, 7])

In [33]:
# notice difference
# from the beginning of rows - get all 
# from the beginning of columns - get all 
x2[0:,:]

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [34]:
# works like:
x2[:,:]

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [35]:
# from the index of 0 of rows get one 
# from the beginning of the columns get all to the end 
x2[0], x2[0,:]

(array([3, 1, 3, 7]), array([3, 1, 3, 7]))

In [36]:
# subarrays as no-copy views 
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [37]:
x2_sub = x2[:2,:2]
x2_sub 

array([[3, 1],
       [4, 0]])

In [38]:
x2_sub[0,0] = 99  # modify the original over view 
x2 

array([[99,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [39]:
x2_sub_copy = x2[:2,:2].copy()
x2_sub_copy 

array([[99,  1],
       [ 4,  0]])

In [40]:
x2_sub_copy[0,0] = 42 
x2 

array([[99,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [41]:
# reshaping of arrays 
# traverse from one dimension to many 
grid = np.arange(1,10).reshape(3,3)
grid 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
x = np.array([1,2,3])

# create an output with "1" row and "3" columns in each 
out = x.reshape((1,3))  # row vector via reshape 
print(out)

# create an output with "3" rows and "1" columns in each 
out = x.reshape((3,1))  # column vector via reshape 
print(out)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [46]:
# shorhand with np.newaxis 
# put a notice that for "1" dimensional array we use [_,_] notation 
# (!) readed: "np.newaxis" = 1 from this axis, ":" all from original to this axis

out = x[np.newaxis, :] # == x.reshape((1,3))
print(out)

out = x[:, np.newaxis] # == x.reshape((3,1))
print(out)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [47]:
# concatenation of arrays 

x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [48]:
z = np.array([99,99,99])
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [49]:
grid = np.array([
    [1,2,3],
    [4,5,6]
])

In [50]:
# concatenate along the first axis (from top to bottom)
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [51]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [52]:
# vertically stack the arrays 
np.vstack([x,grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [53]:
# horizontally stack the arrays 
y = np.array([
    [99],
    [99]
])
np.hstack([grid,y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [54]:
# splitting the arrays 
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x, [3,5]) # split at 3, split at 5
x1,x2,x3

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))

In [56]:
grid = np.arange(16).reshape(4,4)
grid 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
# vertical split (divide by number of rows)
upper,lower = np.vsplit(grid,[2])
upper, lower 

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [58]:
# horizontal split (divide by number of columns)
left,right = np.hsplit(grid,[2])
left,right

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))