In [1]:
 # straightforward approach with the loops:
import numpy as np 
rng = np.random.default_rng(seed = 1701)


In [2]:
def compute_reciprocal(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output 

values = rng.integers(1,10,size=5)
compute_reciprocal(values)

array([0.11111111, 0.25      , 1.        , 0.33333333, 0.125     ])

In [3]:
# approach with ufunc (implemented in "C" vector operations)
1.0 / values 

array([0.11111111, 0.25      , 1.        , 0.33333333, 0.125     ])

In [6]:
print(np.arange(1,6))
print(np.arange(5))
np.arange(5) / np.arange(1,6)

[1 2 3 4 5]
[0 1 2 3 4]


array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [7]:
# ufunc not limited with one dimensional arrays
x = np.arange(9).reshape((3,3))
2 ** x 

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [8]:
# array arithmetic
x = np.arange(4)
x, x+5, x-5, x*2, x/2, x//2

(array([0, 1, 2, 3]),
 array([5, 6, 7, 8]),
 array([-5, -4, -3, -2]),
 array([0, 2, 4, 6]),
 array([0. , 0.5, 1. , 1.5]),
 array([0, 0, 1, 1]))

In [9]:
-(0.5*x + 1) **2

array([-1.  , -2.25, -4.  , -6.25])

In [10]:
np.add(x,2)  # original operation 

array([2, 3, 4, 5])

In [13]:
# absolute value
x = np.array([-2,-1,0,1,2])
abs(x), np.absolute(x)

(array([2, 1, 0, 1, 2]), array([2, 1, 0, 1, 2]))

In [15]:
# trigonometric functions 
theta = np.linspace(0,np.pi, 3)
theta, np.sin(theta),np.cos(theta),np.tan(theta)

(array([0.        , 1.57079633, 3.14159265]),
 array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16]),
 array([ 1.000000e+00,  6.123234e-17, -1.000000e+00]),
 array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16]))

In [16]:
# exponents and logarithms
x = [1,2,3]
x, np.exp(x), np.exp2(x), np.power(3.,x)

([1, 2, 3],
 array([ 2.71828183,  7.3890561 , 20.08553692]),
 array([2., 4., 8.]),
 array([ 3.,  9., 27.]))

In [18]:
# specifying output
x = np.arange(5)
y = np.empty(5)
np.multiply(x,10,out=y)
y 

array([ 0., 10., 20., 30., 40.])

In [19]:
y = np.zeros(10)
np.power(2,x, out=y[::2])
y 

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [20]:
# aggregation 

x = np.arange(1,6)
np.add.reduce(x)

15

In [21]:
np.multiply.reduce(x)

120

In [22]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [26]:
# outer products 
x = np.arange(1,6)
y = np.arange(10,16)
np.multiply.outer(y,x)

array([[10, 20, 30, 40, 50],
       [11, 22, 33, 44, 55],
       [12, 24, 36, 48, 60],
       [13, 26, 39, 52, 65],
       [14, 28, 42, 56, 70],
       [15, 30, 45, 60, 75]])