In [1]:
# fancy indexing:
# pass an array of inidices 
# to access array of elements at once 

import numpy as np 
rng = np.random.default_rng(seed = 1701)

In [2]:
x = rng.integers(100,size=10)
x 

array([90, 40,  9, 30, 80, 67, 39, 15, 33, 79])

In [3]:
# access three different elements 
[x[3],x[7],x[2]]

[30, 15, 9]

In [4]:
# with the fancy indexing:
ind = [3,7,4]
x[ind]

array([30, 15, 80])

In [6]:
ind = np.array([
    [3,7],
    [4,5]
    ])
x[ind]      # original array was reshaped by index

array([[30, 15],
       [80, 67]])

In [7]:
# in multiple dimension
X = np.arange(12).reshape((3,4))
X 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
row = np.array([0,1,2])
col = np.array([2,1,3])
X[row,col]      # [0,2],[1,1],[2,3]

array([ 2,  5, 11])

In [9]:
# combine a column vector and a row vector 
X[row[:,np.newaxis],col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [10]:
row[:,np.newaxis] * col 

array([[0, 0, 0],
       [2, 1, 3],
       [4, 2, 6]])

In [11]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
# combine funcy and simple indices 
X[2, [2,0,1]]       # 2.2, 2.0, 2.1

array([10,  8,  9])

In [15]:
# funcy indexing with the slicing 
X[1:, [2,0,1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [17]:
# fancy indexing and masking 
mask = np.array([True, False, True, False])
X[row[:,np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [19]:
# modifying values with fancy indexing 

x = np.arange(10)
i = np.array([2,1,8,4])
x[i] = 99    # change many of values at once 
x

array([ 0, 99, 99,  3, 99,  5,  6,  7, 99,  9])

In [20]:
x[i] -= 10  # change many of values at once 
x 

array([ 0, 89, 89,  3, 89,  5,  6,  7, 89,  9])

In [21]:
# repeated indices cause problems 

x = np.zeros(10)
x[[0,0]] = [4,6]  # 4 is gone 
x 

array([6., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
# repeated operation:
print(i)                # index for repeating 
x = np.zeros(10)
np.add.at(x,i,1)        # insert value at repeated index 
x 

[2 1 8 4]


array([0., 1., 1., 0., 1., 0., 0., 0., 1., 0.])