In [1]:
# sorting arrays 
L = [1,5,2,4]
sorted(L)

[1, 2, 4, 5]

In [2]:
L.sort()
L

[1, 2, 4, 5]

In [3]:
sorted("python")

['h', 'n', 'o', 'p', 't', 'y']

In [4]:
# fast sorting in numpy: np.sort , np.argsort
import numpy as np 

x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [5]:
x.sort() # inplace 
x 

array([1, 2, 3, 4, 5])

In [6]:
# return indices of sorted elements:
x = np.array([2,1,4,3,5])
i = np.argsort(x)
i 

array([1, 0, 3, 2, 4])

In [7]:
# use fancy indexing with argssort to get an array of sorted:
x[i]

array([1, 2, 3, 4, 5])

In [8]:
# sorting along rows and columns 
rng = np.random.default_rng(seed = 42)
X = rng.integers(0,10, (4,4))
X 

array([[0, 7, 6, 4],
       [4, 8, 0, 6],
       [2, 0, 5, 9],
       [7, 7, 7, 7]])

In [9]:
# sort each column of X 

# axis along which is sorted 
# axis=0 => columns (exclude rows)
# axis=1 => rows (exclude columns)

np.sort(X, axis=0)

array([[0, 0, 0, 4],
       [2, 7, 5, 6],
       [4, 7, 6, 7],
       [7, 8, 7, 9]])

In [10]:
# sort each row of X 
np.sort(X, axis=1)

array([[0, 4, 6, 7],
       [0, 4, 6, 8],
       [0, 2, 5, 9],
       [7, 7, 7, 7]])

In [43]:
# partial sorts: partioning 
# find smallest values of the array


# smallest on the left, remaining to the right 
# result is the array with the smallest k values 

x = np.array([23,77,76,44,88,22,10])
np.partition(x,2)

array([10, 22, 23, 44, 88, 77, 76])