In [1]:
# structured data: numpy's structured arrays (record arrays) for compound 
import numpy as np  

In [3]:
# three arrays to store compoun data:
name = ["alice","bob","cathy","doug"]
age = [25,45,37,19]
weight = [55.0, 85.5, 68.0, 61.5]

In [6]:
# use a compound data type for structured arrays 

# part 1: create an container array 
data = np.zeros(
    4, 
    dtype={"names":("name","age","weight"),
           "formats":("U10","i4","f8")}        
)
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [7]:
# part 2: fill container with data
data["name"] = name 
data["age"] = age 
data["weight"] = weight 
data 

array([('alice', 25, 55. ), ('bob', 45, 85.5), ('cathy', 37, 68. ),
       ('doug', 19, 61.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [8]:
# get all names 
data["name"]

array(['alice', 'bob', 'cathy', 'doug'], dtype='<U10')

In [9]:
# get first row of data 
data[0]

('alice', 25, 55.)

In [10]:
# get the name from the last row 
data[-1]["name"]

'doug'

In [12]:
# selection: get names where age is under 30 
data[
    data["age"] < 30
]["name"]

array(['alice', 'doug'], dtype='<U10')

In [13]:
# exploring structured array creation 

# dictionary method to specify compound data-type:
np.dtype({
    "names":("name","age","weights"),
    "formats":("U10","i4","f8")
})

dtype([('name', '<U10'), ('age', '<i4'), ('weights', '<f8')])

In [14]:
# pythonic types

np.dtype({
    "names":("name","age","weight"),
    "formats":((np.str_,10),int,np.float32)
})

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f4')])

In [16]:
# if names doesn't matter - we can specify only types 
np.dtype("S10,i4,f8")

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [17]:
# more advanced compound types 

# each element consists of an id and 3x3 matrix:
tp = np.dtype([
    ("id","i8"),("mat","f8",(3,3))
])
X = np.zeros(1,dtype = tp)
print(X[0])
print(X["mat"][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
# record arrays: structured arrays with a twist 
data["age"]

array([25, 45, 37, 19], dtype=int32)

In [19]:
data_rec = data.view(np.recarray)
data_rec.age 

array([25, 45, 37, 19], dtype=int32)